# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "/Users/hellohidi/iOSProject/heylets-iOS/Projects/App/Heylets-iOS.xcodeproj")
    build_app(scheme: "Heylets-iOS-DEV")
    
    api_key = app_store_connect_api_key(
      key_id: "9C383R824M",
      issuer_id: "1c043202-f6d3-487a-8236-0d70beae8b38",
      key_filepath: "./fastlane/AuthKey_9C383R824M.p8",
      in_house: false
    )
    
    upload_to_testflight(api_key: api_key)
  end
end

